name: pr-validation-wf
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
     branches:
       - develop
jobs:
  pr-validation-job:
   runs-on: ubuntu-latest
   steps:
     - name: welcome steps
       run: echo "Welcome To the GitHub Actions"
     - name: second step
       run: echo "The is second step"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2 Step 1
      - run: echo "The is Step 1 of job 2"
