name: pr-validation-wf
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
     branches:
       - develop
jobs:
  pr-validation-job:
   runs-on: ubuntu-latest
   steps:
     - name: welcome steps
       run: echo "Welcome To the GitHub Actions"
